# Generated by Django 4.2.1 on 2023-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_category_image_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='lg_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='large Size'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sl_size',
            field=models.CharField(default=0, max_length=20, verbose_name='Small Size'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
    ]
