# Generated by Django 4.2.1 on 2023-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_lg_size_menu_sl_size_delete_itemsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='lg_size',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='sl_size',
        ),
        migrations.AddField(
            model_name='menu',
            name='CAL',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CAL'),
        ),
        migrations.AddField(
            model_name='menu',
            name='SR',
            field=models.CharField(default=0, max_length=20, verbose_name='SR'),
            preserve_default=False,
        ),
    ]
