# Generated by Django 4.2.1 on 2023-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_menu_lg_size_remove_menu_sl_size_menu_cal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='العربية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='الانجليزية'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='العربية'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='الانجليزية'),
        ),
    ]
